### ISSUE TITLE
Marocco homepage needs to be fixed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#10]
https://ma.openfoodfacts.org/
The "Product from the app to be completed" needs to be added.

**Comment by CharlesNepote** [comment]
What? Where?

The [page exists](https://ma.openfoodfacts.org/%D8%A7%D9%84%D9%88%D9%84%D8%A7%D9%8A%D8%A9/en:to-be-completed) and the link also exists on the home page.

Fixed?
