### ISSUE TITLE
Send Test email is not working for forum

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-infrastructure#105]
https://forum.openfoodfacts.org/admin/email
=> Send Test Email => _There was a problem sending the test email. Please double-check your mail settings, verify that your host is not blocking mail connections, and try again._

**Comment by CharlesNepote** [comment]
Sources:
* https://meta.discourse.org/t/troubleshooting-email-on-a-new-discourse-install/16326
* https://github.com/openfoodfacts/openfoodfacts-infrastructure/blob/a6890b0ab20b3dcb687997054ed09603ac37603e/docs/mail.md

```bash
cat /var/discourse/containers/app.yml
[...]
  ## TODO: The SMTP mail server used to validate new accounts and send notifications
  # SMTP ADDRESS, username, and password are required
  # WARNING the char '#' in SMTP password can cause problems!
  DISCOURSE_SMTP_ADDRESS: 10.0.0.1
  DISCOURSE_SMTP_PORT: 25
  #DISCOURSE_SMTP_USER_NAME: user@example.com
  #DISCOURSE_SMTP_PASSWORD: pa$$word
  DISCOURSE_SMTP_ENABLE_START_TLS: false           # (optional, default true)
  #DISCOURSE_SMTP_DOMAIN: discourse.example.com    # (required by some providers)
  #DISCOURSE_NOTIFICATION_EMAIL: noreply@discourse.example.com    # (address to send notifications from)
[...]
```

I changed:
```bash
  DISCOURSE_SMTP_ADDRESS: pmg.openfoodfacts.org
  DISCOURSE_SMTP_PORT: 25
```

Then I:
`/var/discourse/launcher rebuild app`

**Comment by CharlesNepote** [comment]
With @cquest help. Thanks.

**Comment by alexgarel** [comment]
@CharlesNepote I start adding documentation https://github.com/openfoodfacts/openfoodfacts-infrastructure/pull/107
