### ISSUE TITLE
URL Shortener for Open Food Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#122]
### What
We used in the past few days 2 different URL shortener (Linktree, one 1 don't remember) for Instagram bio and shortlink for journalists.
We could use a URL Shortener for Open Food Facts (either 3rd party hosted or self-hosted) with our own domain

**Comment by alexgarel** [comment]
Is this so important ? I mean our domain name per se is already long !
Could we instead use a url shortener from one of the "Chatons" ? https://alt.framasoft.org/fr/framalink

**Comment by CharlesNepote** [comment]
A URL shortener has been created with the combination of:
* a new subdomain: link.openfoodfacts.org
* our blog engine (wordpress) with the "redirect" plugin

To manage redirects: https://blog.openfoodfacts.org/wp-admin/tools.php?page=redirection.php
