### ISSUE TITLE
VM for the Taxonomy Editor

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#123]
### OS
Debian last Stable.

### Local disk space
[Explain if > 32 Gb.]

### Shared disk space
[Explain if > 1 Tb.]

### RAM
[Explain if > 4 Gb.]

### Nb of CPU
[Explain if > 4.]

### Main software bricks
Python, probably PostgreSQL, probably Apache for lightweight API serving from Docker

### Reverse proxy
[On OFF infra all web services use a reverse proxy. Do you need it? What's the name of the service (FQDN, eg. myservice.openfoodfacts.org). Note: port 443 default for extern entries (reverse proxy) and 80 for intern (your machine).]
taxonomy-editor.openfoodfacts.org

### Usage
Taxonomy Editor

### Machine administrators
https://github.com/aadarsh-ram.keys

**Comment by alexgarel** [comment]
It's not a specific VM it's on docker staging VM (and docker prod VM)
