### ISSUE TITLE
VM for the Community Portal

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#124]
### OS
Debian last Stable.

### Local disk space
[Explain if > 32 Gb.]

### Shared disk space
[Explain if > 1 Tb.]

### RAM
[Explain if > 4 Gb.]

### Nb of CPU
[Explain if > 4.]

### Main software bricks
Python/Django, probably PostgreSQL, probably Apache and all Dockerized

### Reverse proxy
[On OFF infra all web services use a reverse proxy. Do you need it? What's the name of the service (FQDN, eg. myservice.openfoodfacts.org). Note: port 443 default for extern entries (reverse proxy) and 80 for intern (your machine).]
cantina.openfoodfacts.org

### Usage
Community Portal

### Machine administrators
https://github.com/sumit-158.keys

### Part of
- https://github.com/openfoodfacts/community-portal/issues/2

**Comment by alexgarel** [comment]
I close this because:
* if it was to be deployed it would be on a docker (so on staging VM)
* project is not yet really active (abandoned in favor of https://github.com/openfoodfacts/facets-knowledge-panels)
