### ISSUE TITLE
Keep renewing the old blog SSL cert

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#137]
### What
Keep renewing the old blog SSL cert

**Comment by teolemon** [comment]
OBF Wiki redirect broken as well

**Comment by alexgarel** [comment]
@teolemon don't you think we should instead point to a CNAME to point to new blog and handle a redirect in NGINX ?

**Comment by alexgarel** [comment]
Can you give me all previous links ?

**Comment by alexgarel** [comment]
Links are https://fr.openfoodfacts.org https://en.openfoodfacts.org

Both dns entry where already redirecting to proxy1.openfoodfacts.org

This was a bad configuration of the nginx where the http section was removed. Only having the https section, certbot is unable to answer to challenges.
I restored a http section in fr.blog.conf and en.blog.conf and launch certbot to reinstall certificates.

**Comment by teolemon** [comment]
thanks @alexgarel
