### ISSUE TITLE
Create a test odoo instance

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-infrastructure#139]
I will shortly work on adding entries to the CRM through the test platform. I would need an odoo instance for that :-)

see https://github.com/openfoodfacts/openfoodfacts-server/issues/7296

**Comment by CharlesNepote** [comment]
Staging have been created and is [documented](https://github.com/openfoodfacts/openfoodfacts-infrastructure/blob/develop/docs/odoo.md#create-a-test-environment-from-production-instance).
