### ISSUE TITLE
Deploy docs to github pages with mkdocs

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-infrastructure#148]
This will make documentation more readable.

Note: look how it's done in openfoodfacts-server or robotoff.

**Comment by trnl** [comment]
I can work on that.

**Comment by alexgarel** [comment]
@trnl :+1:

**Comment by alexgarel** [comment]
yes @sumit-158 you can :-)

**Comment by alexgarel** [comment]
@sumit-158 I have made some changes directly to the develop branch, after I saw it did not deploy ! (mainly fixing default branch name: main --> develop) and the github action.

I also had to change settings in github repository (there is a section for pages).

It's now deployed :tada: 
https://openfoodfacts.github.io/openfoodfacts-infrastructure/

**Comment by sumit-158** [comment]
@alexgarel 👍👍
