### ISSUE TITLE
Add nvme disks on off1 (production Product Opener) and off2 (production MongoDB) -- install Feb 15th 2021

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-infrastructure#15]
The NVME disks will be used to store products .sto files (currently 170 Gb) on off1, and the MongoDB database (currently 20 Gb) on off2.

off2 in particular has lots of cpu usage waiting for disks. Hopefully that will help MongoDB timeout issues (e.g. https://github.com/openfoodfacts/openfoodfacts-server/issues/4754 )

http://supervision2.openfoodfacts.bu.gs/

![image](https://user-images.githubusercontent.com/8158668/104809201-c80a9580-57eb-11eb-954c-a69b98b6b05f.png)

**Comment by stephanegigandet** [comment]
Disks have been ordered and received and will be installed on Wednesday.

**Comment by CharlesNepote** [comment]
Disks couldn't be installed due to lack of place. We have ordered "risers". We're waiting for them (2-3 weeks).

**Comment by stephanegigandet** [comment]
@cquest will install the new disks tomorrow around 2pm.

**Comment by cquest** [comment]
2x 1TB NVMe for off1 (priority: .sto storage)
2x 256GB NVMe for off2 (priority: mongodb storage)

**Comment by cquest** [comment]
.sto are now stored on NVMe SSD disk, using ZFS in separate datasets for each project: off/obf/opf/opff

Replication is done on off2, using ZFS snapshots and incremental send/recv.
Initial replication time: 23'
Differential replication time (every 15mn): typically under 20s.

No more rsync lasting hours or days !
