### ISSUE TITLE
Matomo randomly over memory

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#170]
### What
- Matomo randomly over memory

### Error msg
Matomo encountered an error: Allowed memory size of 262144000 bytes exhausted (tried to allocate 20480 bytes) (which lead to: Allowed memory size of 262144000 bytes exhausted (tried to allocate 20480 bytes))

**Comment by alexgarel** [comment]
https://matomo.org/faq/troubleshooting/faq_95/

**Comment by alexgarel** [comment]
I set memory limit from 250M to 2048M, let's see.
