### ISSUE TITLE
[RFD] Deploy an important bugfix for Hunger Games

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#18]
Currently, the logo annotation game is not working due to a bug in Hunger Games that was fixed. 

The deployment guide (5 commands to execute) is here: https://docs.google.com/document/d/1k_llVzpOhx6hZZJydYgeywlRz9MX8iCb9THk4tzw0uw/edit#heading=h.8h7z9zl1zdcv

**Comment by ocervell** [comment]
@teolemon can this be closed ?

**Comment by teolemon** [comment]
yes, thanks @ocervell
