### ISSUE TITLE
Rsync off1-->off2-->ovh3 problems (and eventually remove non existing image file on target when we rsync them)

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-infrastructure#180]
**Describe the bug**
We rsync images file from off1 to off2 and from off2 to ovh3, but there is no `-delete`, so removed file remains in off2 and ovh3.

**Expected behavior**
As we prepare migration, this would be better to remove those.

Thus, add the -delete flag to rsync commands.

**Comment by alexgarel** [comment]
In fact we have far more problem than that:

1. the ssh key of ovh3 was not approved on off2
2. there is not even an off account on ovh3 (it's raphael0202 indeed that get the id)
3. the way rsync commands are written it would not event work… (too many arguments on command line)
Indeed ovh3 images file are not up to date at all (this was'nt obvious because of the fact that we did not refresh the zfs clones because of the presence of production dockers on staging VM…).

Done:
1. Accepted key of ovh3 on off2
2. added off2 off key to authorized keys on raphael0202 account on ovh3

To do:

1. pass the off1 --> off2 sync to root to avoid all errors we currently get with file permissions that obstrued the image rsync and add the --delete flags.
3. change the rsync script to avoid problems with too many arguments

**Comment by alexgarel** [comment]
Another option to speed up off1 --> off2 sync is to use rsync daemon (as it is safe there).

**Comment by stephanegigandet** [comment]
> * pass the off1 --> off2 sync to root to avoid all errors we currently get with file permissions that obstrued the image rsync and add the --delete flags.

Can we try to solve the errors instead? Everything we transfer should be owned by the off user, if it's not the case, then it is very likely to cause other errors for other processes than rsync.

**Comment by alexgarel** [comment]
Ok, I'll look at errors.

**Comment by alexgarel** [comment]
A command I use to find files that are not accessible:

```bash
u=off g=off ; ionice -c 3 find off off-pro foodbattle ! \( \( -user "$u" -perm -u=r \) -o   \( ! -user "$u" -group "$g"  -perm -g=r \) -o \( ! -user "$u" !  -group "$g"  -perm -o=r \) \) | tee /tmp/srv2-not-off.log
```

(taken from https://unix.stackexchange.com/questions/88573/find-files-that-a-user-can-not-read)

**Comment by alexgarel** [comment]
I moved the rsync in crontab to have it done by root (also move the certificate in root directory).

See https://github.com/openfoodfacts/openfoodfacts-infrastructure/pull/181

I will look at it tomorrow.

I still have some directories that I think we should clean. directories of users and products that have moved to zfs.

@stephanegigandet, I think on off1 we should remove:

```
/srv/obf/products.old
/srv/off-pro/products.old
/srv/opf/products.old
/srv/opff/products.old
```

On off2 we should remove:
```
/srv/obf/products.old
/srv/off/products.old
```

but also (as they should simply point to zfs):
```
/srv/obf/products
/srv/off-pro/products
/srv/opf/products
/srv/opff/products
```

**Comment by stephanegigandet** [comment]
@alexgarel Agreed for all the dirs listed above.

**Comment by alexgarel** [comment]
On off1 all directories listed above are removed

On off2 I removed `/srv/off/products.old` the rest is happening.

**Comment by alexgarel** [comment]
all data removed. I close this ticket for now. We continue on https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/187
