### ISSUE TITLE
VM for robotoff (robotoff.openfoodfacts.org)

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-infrastructure#20]
### OS
Debian last Stable.

### OS disk space
32 Gb

### Data disk space
100 Gb

### RAM
8 Gb 

(may need to be adjusted later)

### Nb of CPU
4

### Main software bricks

robotoff, elastic search, tensorflow, postgresql

### Reverse proxy

robotoff.openfoodfacts.org

### Usage

real time and batch predictions

### Machine administrators

alex-marty
raphael0202
stephane

**Comment by cquest** [comment]
you should be able to connect with:

ssh -J ovh1.openfoodfacts.org 10.1.0.103
