### ISSUE TITLE
Matomo complains we're using an EOL PHP

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#201]
### What
- Matomo complains we're using an EOL PHP
- "The PHP version 7.3 you are using has reached its End of Life (EOL). You are strongly urged to upgrade to a current version, as using this version may expose you to security vulnerabilities and bugs that have been fixed in more recent versions of PHP."

**Comment by alexgarel** [comment]
This needs an upgrade of the container to a more recent debian.
