### ISSUE TITLE
Matomo would like us to delete some files for file integrity reasons

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#202]
### What
- Matomo would like us to delete some files for file integrity reasons

<img width="992" alt="image" src="https://user-images.githubusercontent.com/1689815/226863776-67fb0e6d-00c2-4f99-88e2-8b6f8b5ecfa1.png">

**Comment by CharlesNepote** [comment]
Not very important, but fixed.
