### ISSUE TITLE
Error with Join Slack Page

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#204]
### Discussed in https://github.com/openfoodfacts/openfoodfacts-server/discussions/8248

<div type='discussions-op-text'>

<sup>Originally posted by **ReedAndreas** March 24, 2023</sup>
Hi all! I am looking to join the slack at https://slack.openfoodfacts.org/ but am receiving a 504 timeout error on nginx. Any insight on how I can get on the slack given this problem?</div>

**Comment by teolemon** [comment]
Not completely down, but flaky

**Comment by alexgarel** [comment]
I replaced by a simple web page and a hard coded invitation. It will brake at some point… so I also add a message to write us when it breaks !

See https://github.com/openfoodfacts/openfoodfacts-infrastructure/blob/develop/docs/slackin.md
