### ISSUE TITLE
Made Near Me is OoO

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#214]
### What
Made Near Me is OoO: https://madenear.me/

![image](https://user-images.githubusercontent.com/1689815/232032222-9cefdb1d-762a-4291-88fb-ea1fd99e3c1b.png)

**Comment by alexgarel** [comment]
The problem is that we run a really big query to create it. Right now with our Mongo on temporary machine it's a bit too much.
