### ISSUE TITLE
SMART problem on ovh3 for disk sdc

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-infrastructure#219]
Yesterday we had a problem on ovh3 - (so images were not serving), and the last message in syslog before bugs was about sdc 
```bash
May  4 15:09:40 ovh3 smartd[15638]: Device: /dev/sdc [SAT], 8 Currently unreadable (pending) sectors
``` 

@cquest has seen that /dev/sdc have failed complete tests since 3 monthes !

```
smartctl -a /dev/sdc
```

We didn't get any email alert for that.

**Comment by alexgarel** [comment]
I think @cquest has launched a scrub to try to fix sectors.

**Comment by cquest** [comment]
a ZFS scrub just makes sure all data stored has a good checksum.

Bad sectors are not remapped in this process as far as I know.
Remapping only occurs at the disk firmware level when some data is written to a bad sector.

A SMART scan can help determine which block are bad, then we can on them using dd to let the firmware remap them.

**Comment by alexgarel** [comment]
Finally this disk was replaced by OVH on 2023-07-16. See https://github.com/openfoodfacts/openfoodfacts-infrastructure/blob/develop/docs/reports/2023-07-16-ovh3-sdc-broken.md
