### ISSUE TITLE
Remove replication of docker prod to ovh1 and augment disk size

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-infrastructure#236]
**Describe the bug**
We are blocked by the disk size on docker-prod since a long time.

There is space on ovh2, where the VM live, but not on ovh1 where it is live replicated (also replicated on ovh3).

**solution**

Remove replication from ovh1 and augment disk space.

**Comment by alexgarel** [comment]
We removed the replication (but did not seem effective), @raphael0202 will look at it.

**Comment by alexgarel** [comment]
FTR: https://openfoodfacts.github.io/openfoodfacts-infrastructure/promox/#adding-space-on-a-qemu-disk

**Comment by raphael0202** [comment]
Replication was successfully removed.

**Comment by alexgarel** [comment]
@cquest @CharlesNepote, FYI
