### ISSUE TITLE
CSV export is not resilient

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-infrastructure#246]
On openfoodfacts.org:
* [ ] there is no alert anywhere when CSV export fails (email to root@openfoodfacts.org, online log, logs on local machine...)
* [ ] there is no documentation on how to relaunch CSV export (I guess https://github.com/openfoodfacts/openfoodfacts-server/blob/main/scripts/export_database.pl is launched somewhere but I was unable to find in any crontab on off1)

That's annoying because CSV exports are used for many tasks such as:
* data quality statistics, including [data quality dashboard](https://mirabelle.openfoodfacts.org/-/dashboards)
* data quality daily
* ... and probably many usages we don't know

**Comment by alexgarel** [comment]
export_database.pl is launched from gen_feeds_daily_off.sh

**Comment by CharlesNepote** [comment]
Thanks @alexgarel. So I can see export_database.pl is launched without arguments and dependencies, so I'm going to launch it (maybe this evening) to see what is the issue.

If I have time left I will modify the .sh script to tee output to a log file.

**Comment by CharlesNepote** [comment]
I have manually launched the script? We're facing a MongoDB issue, but I don't know how to solve it.
```(bash)
cd /srv/off/scripts
export PERL5LIB="../lib:${PERL5LIB}"
./export_database.pl | tee /srv2/off/html/data/export_database.log
[...]
2930000 
2931000 
2932000 
<h1>Software error:</h1>
<pre>MongoDB::DatabaseError: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.</pre>
<p>
For help, please send mail to this site's webmaster, giving this error message 
and the time and date of the error.

</p>
[Tue Aug 15 00:20:12 2023] export_database.pl: MongoDB::DatabaseError: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.
```
