### ISSUE TITLE
Upgrade off2 to bookworm ?

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-infrastructure#249]
[A new feature to read more barcode](https://github.com/openfoodfacts/openfoodfacts-server/pull/8911/files) developed by @hangy would require to move to bookworm in production.

Off2 was installed with a bullseye distribution.

The migration of off instances on off2 is still a work in progress.

Do we want to upgrade off2 to bookworm (doing so before off swith to off2 might be better).

Or is it ok to install bookworm containers on a bullseye host ? And thus only migrate the container ?

Or do we instead stick to bullseye for now and manually compile a deb of the needed library for bullseye ?

**Comment by alexgarel** [comment]
@stephanegigandet, @hangy and @cquest, opinions welcome.

**Comment by hangy** [comment]
As discussed in https://github.com/openfoodfacts/openfoodfacts-server/pull/8911/files#r1322987464, the upgrade is probably not necessary after all.
