### ISSUE TITLE
update geoip database on off1

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-infrastructure#270]
ls -lrt /usr/local/share/GeoLite2-Country/GeoLite2-Country.mmdb
-rw-r--r-- 1 2000 2000 3714586 Mar 11  2019 /usr/local/share/GeoLite2-Country/GeoLite2-Country.mmdb

**Comment by alexgarel** [comment]
On off2, where we have now migrated, it's updated automatically.
