### ISSUE TITLE
Containers (x2) to build a replica set for OFF database

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-infrastructure#28]
2 containers to hosts 2 mongodb replicas. The two containers should be hosted on two different machines.

### OS
Debian 10

### Local disk space
50 GB (DB = 20 GB).

### Shared disk space
0

### RAM
32 GB

### Nb of CPU
4

### Main software bricks
Mongodb.

### Reverse proxy
* mongo2.openfoodfacts.org
* mongo3.openfoodfacts.org

### Usage
OFF database replicas:
* to let some apps use OFF database replica in readonly
* to allow automatic failover and automatic recovery

### Machine administrators
@CharlesNepote
@stephanegigandet
@syl10100

**Comment by CharlesNepote** [comment]
Both containers are now working, with mongodb running.

MongoDB install: https://gist.github.com/CharlesNepote/13198c2ed336fc64cb674d63876e8d99

## MongoDB replication
Resources:
* https://www.tutorialspoint.com/mongodb/mongodb_replication.htm
* https://www.mongodb.com/basics/replication

Needs:
* _MongoDB installed on three or more nodes_
* _Each of the nodes in the cluster will need to be able to communicate with the others over a standard port (27017 by default)_
* _each replica set member needs to have a hostname that is resolvable from the others_
* _Establish a virtual private network. Ensure that your network topology routes all traffic between members within a single site over the local area network._
* _Configure access control to prevent connections from unknown clients to the replica set._
* _Configure networking and firewall rules so that incoming and outgoing packets are permitted only on the default MongoDB port and only from within your deployment. See the IP Binding considerations._
* _Ensure that each member of a replica set is accessible by way of resolvable DNS or hostnames._

**Comment by syl10100** [comment]
https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/

**Comment by CharlesNepote** [comment]
Things to do:

1. - [x] create containers for mongo2 and mongo3
2. - [x] [install mongodb server](https://gist.github.com/CharlesNepote/13198c2ed336fc64cb674d63876e8d99) on both machines
3. - [x] create linux users on each machine for ..........
4. - [ ] create DNS entries: mongo2.openfoodfacts.org => ovh1.openfoodfacts.org; and mongo3.openfoodfacts.org => ovh2.openfoodfacts.org
5. - [ ] create iptables routing and firewall on ovh1 and ovh2 (restrict traffic from off1, off2, mongo2, mongo3)
6. - [ ] verify we can connect from off2 to mongo2 and mongo3
7. - [ ] convert off2 mongodb into a Replica Set:

- Shut down the standalone mongod instance.
- Restart the instance. Use the --replSet option to specify the name of the new replica set: `mongod --replSet "rs0" --bind_ip localhost,off2.free.org`
- Connect a mongo shell to the mongod instance.
- Use `rs.initiate()` to initiate the new replica set

8. - [ ] add mongo2 and mongo3 to the replica set:

- restart each instance with --replSet "rs0": `mongod --replSet "rs0" --bind_ip localhost,mongo2.openfoodfacts.org`
- connect to each machine
- `rs.add("off2.free.org")`
- control configuration: `rs.conf()`
- control status: `rs.status()`

9. - [ ] possibly, [prevent secondary mongo instances to become primary](https://docs.mongodb.com/manual/tutorial/configure-secondary-only-replica-set-member/) (I'm not sure it's possible with 3 machines)

Feel free to suggest improvements, I'll update the process.

**Comment by syl10100** [comment]
In step  6, we should check that we can connect to mongo2, mongo3 and off2 from any server :  
mongo –host mongo2 –port 27017
mongo –host mongo3 –port 27017
mongo –host off2 –port 27017

**Comment by CharlesNepote** [comment]
> So we should first start an empty mongod on mongo2 and mongo3, to check these connections

Yes, it has already been done (step 2).

I modified the sentence of step 6 to be more clear, thanks:
"verify we can connect from each 3 servers to each others: `mongo --host otherserver --port 27017`"

**Comment by cquest** [comment]
Done ? Can we close this issue ?

**Comment by CharlesNepote** [comment]
Finally, we haven't used these containers.
