### ISSUE TITLE
Robotoff is not honoring credentials anymore

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#31]
- [ ] Robotoff is not honoring credentials anymore
- [ ] We might have forgotten/replicate some mechanism on the new install
https://github.com/openfoodfacts/openfoodfacts-hungergames/blob/e4dccf894d52527b7a1953820e2548b22e58e629/src/robotoff.js

**Comment by raphael0202** [comment]
This cannot be replicated anymore in production, closing the issue.
