### ISSUE TITLE
Status link issue

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/openfoodfacts-infrastructure#346]
Reported by Tim G. on Slack :
_I can't click into any of the statuses on https://status.openfoodfacts.org/ ... seems like an extra slash is being added to the end of URLs, eg, the URL for Main website is https://status.openfoodfacts.org//history/main-website, ("//history"), which results in a 404 page. Replacing the double slash shows the more detailed status page._

**Comment by stephanegigandet** [comment]
Fixed by https://github.com/openfoodfacts/openfoodfacts-upptime/commit/7f6f3235773752381e39b772cffbba6bb1457f36
