### ISSUE TITLE
VM for the dev instance of Robotoff

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#40]
Probably lower specs for dev

### OS
Debian last Stable.

### OS disk space
32 Gb

### Data disk space
100 Gb

### RAM
8 Gb 

(may need to be adjusted later)

### Nb of CPU
4

### Main software bricks

robotoff, elastic search, tensorflow, postgresql

### Reverse proxy

robotoff.openfoodfacts.net

### Usage

real time and batch predictions

### Machine administrators

alex-marty
raphael0202
stephane
yana
olivier

**Comment by ocervell** [comment]
@teolemon can we close this ?

**Comment by teolemon** [comment]
Yes
