### ISSUE TITLE
VM for Tensorflow Model Experimentation

### ISSUE THREAD

**Issue by kulizhsy** [openfoodfacts/openfoodfacts-infrastructure#48]
[All the following limits (RAM, CPU, storage) can be dynamically adjusted later.]

### OS
[What OS do you want? Default to Debian last Stable.]

### Local disk space
[Explain if > 32 Gb.]

### Shared disk space
[Explain if > 1 Tb.]

### RAM
[Explain if > 4 Gb.]

### Nb of CPU
[Explain if > 4.]

### Main software bricks
[This is just for information. The machine is provided bare. Example: PostgreSQL, Node.js, Apache, etc.]

### Reverse proxy
[On OFF infra all web services use a reverse proxy. Do you need it? What's the name of the service (FQDN, eg. myservice.openfoodfacts.org). Note: port 443 default for extern entries (reverse proxy) and 80 for intern (your machine).]

### Usage
[One or two lines.]
I'd like a VM to experiment with training of ML models. No idea on the disk/memory requirements so the defaults should be fine if it's possible to adjust them later.

### Machine administrators
[Default: you. Please indicate your github account name to retrieve your SSH key. Prefer your SSH key published on Github, eg. https://github.com/CharlesNepote.keys 
There should be a main administrator and a co-administrator.]
kulizhsy

**Comment by CharlesNepote** [comment]
The machine has been created. For Tensorflow experiments I choose: 64 GB RAM, 8 cpu, 32 GB SSD. Let me know if we have to change this.

To connect yourself to the machine:
`$ ssh -i ~/.ssh/id_rsa -J kulizhsy@ovh1.openfoodfacts.org kulizhsy@10.1.0.117`

**Comment by teolemon** [comment]
@kulizhsy did you spot this ?

**Comment by kulizhsy** [comment]
Yes, this has been resolved, thanks!
