### ISSUE TITLE
Container for robotoff-net

### ISSUE THREAD

**Issue by ocervell** [openfoodfacts/openfoodfacts-infrastructure#51]
### OS
Debian 11

### Local disk space
92GB

### Shared disk space
0GB

### RAM
16GB (DB 4GB, Services 8GB)

### Nb of CPU
4

### Main software bricks
Robotoff API + Schedulers + Workers, PostgreSQL DB

### Reverse proxy
robotoff.openfoodfacts.net

### Usage
Robotoff .net VM

### Machine administrators
alex-marty
kulizhsy
raphael0202
stephane
ocervell

**Comment by ocervell** [comment]
@kulizhsy for review

**Comment by CharlesNepote** [comment]
Machine created.

**Comment by alexgarel** [comment]
This was moved to a deployment on staging docker VM (200).
