### ISSUE TITLE
Container for robotoff-ml

### ISSUE THREAD

**Issue by ocervell** [openfoodfacts/openfoodfacts-infrastructure#53]
### OS
Debian 11

### Local disk space
192GB [ML models]

### Shared disk space
100GB

### RAM
96GB (Tensorflow, ANN)

### Nb of CPU
8

### Main software bricks
Tensorflow + ElasticSearch

### Reverse proxy
robotoff.openfoodfacts.net

### Usage
Robotoff .net machine learning VM

### Machine administrators
alex-marty
kulizhsy
raphael0202
stephane
ocervell

**Comment by ocervell** [comment]
@kulizhsy for specs review

**Comment by CharlesNepote** [comment]
Machine created. I put 96 GB RAM finally as we have plenty of RAM on this machine and I know models like RAM.

**Comment by alexgarel** [comment]
This was moved to a docker deployment.

See also : https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/81
