### ISSUE TITLE
Container for impactestimator-net

### ISSUE THREAD

**Issue by zond** [openfoodfacts/openfoodfacts-infrastructure#55]
[All the following limits (RAM, CPU, storage) can be dynamically adjusted later.]

### OS
Debian 11

### Local disk space
1Gb

### Shared disk space
0

### RAM
1GB

### Nb of CPU
1

### Main software bricks
https://github.com/openfoodfacts/impactestimator

### Reverse proxy
No need - this one only does requests to productopener.

### Usage
Asynchronously decorate PO products with product-level Eco-score based on https://github.com/openfoodfacts/off-product-environmental-impact.

### Machine administrators
https://github.com/zond.keys
https://github.com/ocervell.keys

**Comment by CharlesNepote** [comment]
Machine created. I put 2 GB of disk as 1 GB is a bit too low.

**Comment by zond** [comment]
Great, how do I reach it? :D

**Comment by CharlesNepote** [comment]
Sorry. The documentation of the CTs-VMs is here:https://wiki.openfoodfacts.org/Infrastructure/VM_cluster (see SSH connexion section to reach it).
The IP address of the CT is 1.0.1.120.

**Comment by alexgarel** [comment]
This container has been removed since a long time ! It was deployed using docker, and we stopped it for now, for it was not giving useful results.
