### ISSUE TITLE
Container for monitoring

### ISSUE THREAD

**Issue by ocervell** [openfoodfacts/openfoodfacts-infrastructure#59]
### OS
Debian 11

### Local disk space
64GB

### Shared disk space
500GB (ovh3 mount)

### RAM
32GB

### Nb of CPU
4

### Main software bricks
Docker: ElasticSearch (Kibana?, Logstash?), Grafana, InfluxDB, Prometheus, Alertmanager 

### Reverse proxy
monitoring.openfoodfacts.org --> port 3000 [Grafana]
monitoring.openfoodfacts.org/metrics --> port 9090 + basic auth [Prometheus UI]
monitoring.openfoodfacts.org/alerts --> port 9093 + basic auth [Alertmanager UI]

### Usage
Monitoring tools.

### Machine administrators
https://github.com/ocervell.keys
https://github.com/teolemon.keys
https://github.com/stephanegigandet.keys
https://github.com/CharlesNepote.keys
https://github.com/cquest.keys

**Comment by cquest** [comment]
CT121 ready to go (if I missed nothing).

Please install docker from docker repo...
