### ISSUE TITLE
Broken assets on Open Pet Food Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#6]
Failed to load resource: the server responded with a status of 404 ()
static.openpetfoodfacts.org/images/favicon/favicon-32x32.png:1 Failed to load resource: the server responded with a status of 404 ()
static.openpetfoodfacts.org/images/favicon/favicon-16x16.png:1 Failed to load resource: the server responded with a status of 404 ()
static.openpetfoodfacts.org/images/favicon/favicon-96x96.png:1 Failed to load resource: the server responded with a status of 404 ()
static.openpetfoodfacts.org/images/favicon/android-chrome-192x192.png:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by CharlesNepote** [comment]
Seems ok now, closing.
