### ISSUE TITLE
Get back old grafana monitoring dashboard

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-infrastructure#73]
We have a new monitoring with grafana, but there were other monitorings on off2.

Can we migrate those.

**Comment by alexgarel** [comment]
I setup the grafana locally:
1. get the docker-compose and adapt it slightly to run on my localhost
2. tar data of grafana-storage (`docker volume inspect` is your friend), copy them to my local volume
3. edit the database with sqlite3 to bypass admin password (see https://community.grafana.com/t/how-do-i-reset-admin-password/23/2)

Get the dashboards from off2 locally and export them.
4. login to my local grafana, export every dashboard.

From what I can see, all dashboards use the influxDB database from off2.
Now what I wonder how is influxDB loaded:
- telegraph on off1 is adding data from the nginx log (`nginx_log`)
- but there is also off_metrics data , but I don't yet know where it comes from !

**Comment by alexgarel** [comment]
@ocervell do you think it would be a good idea to send telegraf data from off1 to influxdb on new monitoring infrastructure ?

**Comment by ocervell** [comment]
Yes, but we should label it with something (telegraf config) to identify where it's coming from.

**Comment by alexgarel** [comment]
@ocervell I've written #74 because it doesn't seem a completly trivial move.

**Comment by CharlesNepote** [comment]
@alexgarel, @raphael0202 I'm closing, feel free to reopen if it is a mistake.
