### ISSUE TITLE
Move TF serving from 200 to 201 (from preprod to prod)

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-infrastructure#81]
The TF serving module is common for preprod and prod. This seems ok for now.
However, because availability of 201 happens late, robotoff-ml was installed on preprod machine.

I think we should move it to 200 (prod machine).

**Comment by alexgarel** [comment]
to discuss with @mithridatea and @CharlesNepote:

should we share tf-serving between prod and preprod, or should we have two distinct services.

**Comment by alexgarel** [comment]
resource I will need for tf serving on 201:

- disk 1 Go minimum
- ram 10G
- cpu it's greedy :-)

**Comment by raphael0202** [comment]
I'm currently switching from Tensorflow Serving to Triton (https://github.com/openfoodfacts/robotoff/issues/622). I'm going to deploy it in preprod.

**Comment by raphael0202** [comment]
The deployment of TF Serving + Triton has been done in production (201).
