### ISSUE TITLE
Setup a mail server

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-infrastructure#83]
Mail from our servers are blocked by google.

We need to setup a mail server that will relay our servers messages.

We have to carefully setup:

- users with credential to allow only our servers to send messages using this relay
- DKIM
- SPF
- MARC

**Comment by alexgarel** [comment]
@cquest this is quite an urgent request.

I know you already start to setup a server on ovh1.
I would be glad if we can work together on this. (and document).

**Comment by CharlesNepote** [comment]
Why not starting the implementation design here?

A good service to test email delivery, if you don't know it yet: https://www.mail-tester.com/

**Comment by alexgarel** [comment]
We just need to clone what is done for OSM (a packaged VM), and then configure all servers.

**Comment by alexgarel** [comment]
Ok I got the mail configured. 

I still have to write the doc, although I put a rough dump here.
[install mail gateway.md](https://github.com/openfoodfacts/openfoodfacts-infrastructure/files/8050704/install.mail.gateway.md)

Latest test on mail-tester: https://www.mail-tester.com/test-g6jk6pdto

What remains to be done:
- [ ] setup DMARC
- [ ] configure off2 / ovh2&3 and every sub machine that needs to send emails
- [ ] documentation

**Comment by alexgarel** [comment]
For DMARC see #99
