### ISSUE TITLE
We have to move monitoring on it's own VM

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-infrastructure#89]
**Describe the bug**
All the monitoring infrastructure is on preprod 200 and this is absolutly not a good idea.
Every-time we want to update the preprod data (the zfs clone containing sto), we have to reboot the machine.

**Expected behavior**

I propose to put monitoring on it's own container, because it is far better when monitoring is independent !

(I propose to gain on 105 or 103 machines resources).

**Comment by alexgarel** [comment]
@CharlesNepote and @cquest do you agree ?

**Comment by alexgarel** [comment]
https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/81 also have the same issue

**Comment by alexgarel** [comment]
I would give:

- at least 150 Go disk  (it is currently around 15G, but this will grow a lot (because of elasticsearch indexing logs))
- possibly 8 cpus (2 for ES, 1 for influx, 1 for prometheus, 1 for the rest, 3 for the querying tools grafana / ES)
- 25 Go (ES needs 12Go, prometheus 3Go, the rest is divided between remaining + a margin of 5Go)

@CharlesNepote could we provision this on ovh1 as a QEMU VM ?

It will then be quite easy to move the monitoring stack there.

**Comment by cquest** [comment]
Own VM or separate hardware outside of the free+OVH bare metals ?

**Comment by alexgarel** [comment]
@cquest do you have a proposition ? 

If we want to lend a server outside, I would take one either in OVH, different DC or at Scaleway
* scaleway dedibox start-2L is around 50€/month (Vat incl.)
* ovh elite vps is around this or more…

@CharlesNepote ?

**Comment by CharlesNepote** [comment]
Let's start with OVH1 I guess. We still have 400 GB of disk and 190 GB RAM free on OVH1, let's use it!

> Own VM or separate hardware outside of the free+OVH bare metals ?

@cquest: why a separate machine?

**Comment by alexgarel** [comment]
I think we'd better start on OVH1 and then move if someone sponsors us a VM.

**Comment by alexgarel** [comment]
It's done:
- documentation PR (report) : https://github.com/openfoodfacts/openfoodfacts-infrastructure/pull/164
- deployment PR: https://github.com/openfoodfacts/openfoodfacts-monitoring/pull/58
