### ISSUE TITLE
Set up ES for Zammad

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#91]
### What
- Set up ES for Zammad to ensure everything can be searched

`
{"error":"Unable to process GET request to elasticsearch URL 'http://localhost:9200/zammad_production_ticket/_doc/_search'. Elasticsearch is not reachable, probably because it's not running or even installed.\n\nResponse:\n#\u003cUserAgent::Result:0x0000561b14f220d0 @success=false, @body=nil, @data=nil, @code=0, @content_type=nil, @error=\"#\u003cErrno::ECONNREFUSED: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for \\\"localhost\\\" port 9200)\u003e\", @header=nil\u003e\n\nPayload:\n{\"query\":{\"bool\":{\"must\":[{\"range\":{\"created_at\":{\"from\":\"2021-12-31T23:00:00Z\",\"to\":\"2022-12-31T22:59:59Z\"}}}],\"must_not\":[{\"term\":{\"state.name.keyword\":\"merged\"}}]}},\"size\":0,\"aggs\":{\"time_buckets\":{\"date_histogram\":{\"field\":\"created_at\",\"interval\":\"month\",\"time_zone\":\"Europe/Paris\"}}},\"sort\":[{\"updated_at\":{\"order\":\"desc\"}},\"_score\"]}\n\nPayload size: 0M"}
`

**Comment by alexgarel** [comment]
@CharlesNepote FYI

**Comment by alexgarel** [comment]
https://docs.zammad.org/en/latest/install/elasticsearch.html relevant documentation. We can use system packages for ES so that  should not be difficult.

**Comment by alexgarel** [comment]
@cquest this is on your server, so I can't do anything. There is no immediate urgency, but we would like to use the knowledge base of zammad to improve user experience. Searching requires to have ES setup (I would also benefit from it for I'm using Zammad for support, and I would be able to search my previous answers).

**Comment by alexgarel** [comment]
@CharlesNepote gives me access to the machine so I will try to do it.

**Comment by alexgarel** [comment]
This is fixed, that was not trivial.

Documentation to be merged there : #96
